all:
	#make clean
	xelatex -interaction=nonstopmode EE6265_HW4_106061531.tex
	xelatex -interaction=nonstopmode EE6265_HW4_106061531.tex
	open EE6265_HW4_106061531.pdf &
clean:
	rm *.aux *.pdf *.log *.out
